framework:
    cache:
        prefix_seed: kgrunwald/stock_bot

        # Redis
        # app: cache.adapter.redis
        # default_redis_provider: '%env(resolve:REDIS_URL)%'

        # system: cache.adapter.system