auth_redirect:
  path: /auth/login
  methods: [POST]
  controller: App\Controller\Oauth2Controller::redirectToAuthentication

auth_callback:
  path: /auth/callback
  methods: [GET]
  controller: App\Controller\Oauth2Controller::callback

auth_logout:
    path: /auth/logout
    methods: [GET,POST]

get_user:
  path: /api/user
  methods: [GET]
  controller: App\Controller\DefaultController::getUserHandler

get_users:
  path: /api/users
  methods: [GET]
  controller: App\Controller\DefaultController::getUsers

home:
  path: /{reactRouting}
  controller: App\Controller\DefaultController::index
  requirements:
    reactRouting: .*