auth_redirect:
  path: /auth/login
  methods: [POST]
  controller: App\Controller\Oauth2Controller::redirectToAuthentication

auth_callback:
  path: /auth/callback
  methods: [GET]
  controller: App\Controller\Oauth2Controller::callback

auth_logout:
    path: /auth/logout
    methods: [GET,POST]

get_user:
  path: /api/user
  methods: [GET]
  controller: App\Controller\DefaultController::getUserHandler

get_users:
  path: /api/users
  methods: [GET]
  controller: App\Controller\DefaultController::getUsers

register: 
  path: /api/register
  methods: [POST]
  controller: App\Controller\DefaultController::register

ping:
  path: /ping
  methods: [GET]
  controller: App\Controller\DefaultController::ping

getPlans:
  path: /api/plans
  methods: [GET]
  controller: App\Controller\DefaultController::getAllPlans

getGoals:
  path: /api/goals
  methods: [GET]
  controller: App\Controller\DefaultController::getAllGoals

getGoal:
  path: /api/goals/{goalId}
  methods: [GET]
  controller: App\Controller\DefaultController::getGoalById

home:
  path: /{reactRouting}
  controller: App\Controller\DefaultController::index
  requirements:
    reactRouting: .*